//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReferenceUKMailQA {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginWebRequest", Namespace="http://www.UKMail.com/Services/Contracts/DataContracts")]
    [System.SerializableAttribute()]
    public partial class LoginWebRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string PasswordField;
        
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UKMWebResponse", Namespace="http://www.UKMail.com/Services/Contracts/DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ServiceReferenceUKMailQA.UKMLogoutResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ServiceReferenceUKMailQA.UKMLoginResponse))]
    public partial class UKMWebResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.ServiceReferenceUKMailQA.UKMWebError[] ErrorsField;
        
        private WebApplication1.ServiceReferenceUKMailQA.UKMResultState ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.ServiceReferenceUKMailQA.UKMWebWarning[] WarningsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.ServiceReferenceUKMailQA.UKMWebError[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebApplication1.ServiceReferenceUKMailQA.UKMResultState Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.ServiceReferenceUKMailQA.UKMWebWarning[] Warnings {
            get {
                return this.WarningsField;
            }
            set {
                if ((object.ReferenceEquals(this.WarningsField, value) != true)) {
                    this.WarningsField = value;
                    this.RaisePropertyChanged("Warnings");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UKMLogoutResponse", Namespace="http://www.UKMail.com/Services/Contracts/DataContracts")]
    [System.SerializableAttribute()]
    public partial class UKMLogoutResponse : WebApplication1.ServiceReferenceUKMailQA.UKMWebResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UKMLoginResponse", Namespace="http://www.UKMail.com/Services/Contracts/DataContracts")]
    [System.SerializableAttribute()]
    public partial class UKMLoginResponse : WebApplication1.ServiceReferenceUKMailQA.UKMWebResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.ServiceReferenceUKMailQA.AccountWebModel[] AccountsField;
        
        private string AuthenticationTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.ServiceReferenceUKMailQA.AccountWebModel[] Accounts {
            get {
                return this.AccountsField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountsField, value) != true)) {
                    this.AccountsField = value;
                    this.RaisePropertyChanged("Accounts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AuthenticationToken {
            get {
                return this.AuthenticationTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationTokenField, value) != true)) {
                    this.AuthenticationTokenField = value;
                    this.RaisePropertyChanged("AuthenticationToken");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UKMWebError", Namespace="http://www.UKMail.com/Services/Contracts/DataContracts")]
    [System.SerializableAttribute()]
    public partial class UKMWebError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UKMResultState", Namespace="http://schemas.datacontract.org/2004/07/UKMWebAPICommon.WebResponses")]
    public enum UKMResultState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Successful = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UKMWebWarning", Namespace="http://www.UKMail.com/Services/Contracts/DataContracts")]
    [System.SerializableAttribute()]
    public partial class UKMWebWarning : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountWebModel", Namespace="http://www.UKMail.com/Services/Contracts/DataContracts")]
    [System.SerializableAttribute()]
    public partial class AccountWebModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.ServiceReferenceUKMailQA.AccountStatusEnum AccountStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.ServiceReferenceUKMailQA.AccountTypeEnum AccountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlternativeRefAliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerRefAliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.ServiceReferenceUKMailQA.RegionEnum RegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TradingAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VATNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.ServiceReferenceUKMailQA.AccountStatusEnum AccountStatus {
            get {
                return this.AccountStatusField;
            }
            set {
                if ((this.AccountStatusField.Equals(value) != true)) {
                    this.AccountStatusField = value;
                    this.RaisePropertyChanged("AccountStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.ServiceReferenceUKMailQA.AccountTypeEnum AccountType {
            get {
                return this.AccountTypeField;
            }
            set {
                if ((this.AccountTypeField.Equals(value) != true)) {
                    this.AccountTypeField = value;
                    this.RaisePropertyChanged("AccountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlternativeRefAlias {
            get {
                return this.AlternativeRefAliasField;
            }
            set {
                if ((object.ReferenceEquals(this.AlternativeRefAliasField, value) != true)) {
                    this.AlternativeRefAliasField = value;
                    this.RaisePropertyChanged("AlternativeRefAlias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactNumber {
            get {
                return this.ContactNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNumberField, value) != true)) {
                    this.ContactNumberField = value;
                    this.RaisePropertyChanged("ContactNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerRefAlias {
            get {
                return this.CustomerRefAliasField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerRefAliasField, value) != true)) {
                    this.CustomerRefAliasField = value;
                    this.RaisePropertyChanged("CustomerRefAlias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Postcode {
            get {
                return this.PostcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostcodeField, value) != true)) {
                    this.PostcodeField = value;
                    this.RaisePropertyChanged("Postcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.ServiceReferenceUKMailQA.RegionEnum Region {
            get {
                return this.RegionField;
            }
            set {
                if ((this.RegionField.Equals(value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TradingAddress {
            get {
                return this.TradingAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.TradingAddressField, value) != true)) {
                    this.TradingAddressField = value;
                    this.RaisePropertyChanged("TradingAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VATNumber {
            get {
                return this.VATNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.VATNumberField, value) != true)) {
                    this.VATNumberField = value;
                    this.RaisePropertyChanged("VATNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountStatusEnum", Namespace="http://www.UKMail.com/Services/Contracts/DataContracts")]
    public enum AccountStatusEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Closed = 94,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 95,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExemptFromStop = 96,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Under7DayReview = 97,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FastTrack = 98,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnStop = 99,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountTypeEnum", Namespace="http://www.UKMail.com/Services/Contracts/DataContracts")]
    public enum AccountTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        International = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EURoad = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Domestic = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MailPackets = 58,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegionEnum", Namespace="http://www.UKMail.com/Services/Contracts/DataContracts")]
    public enum RegionEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        England = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Scotland = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wales = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Northern_Ireland = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebRequest", Namespace="http://www.UKMail.com/Services/Contracts/DataContracts")]
    [System.SerializableAttribute()]
    public partial class WebRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AuthenticationTokenField;
        
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AuthenticationToken {
            get {
                return this.AuthenticationTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationTokenField, value) != true)) {
                    this.AuthenticationTokenField = value;
                    this.RaisePropertyChanged("AuthenticationToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.UKMail.com/Services/Contracts/ServiceContracts", ConfigurationName="ServiceReferenceUKMailQA.IUKMAuthenticationService")]
    public interface IUKMAuthenticationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UKMail.com/Services/IUKMAuthenticationService/Login", ReplyAction="http://www.UKMail.com/Services/Contracts/ServiceContracts/IUKMAuthenticationServi" +
            "ce/LoginResponse")]
        WebApplication1.ServiceReferenceUKMailQA.UKMLoginResponse Login(WebApplication1.ServiceReferenceUKMailQA.LoginWebRequest loginWebRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UKMail.com/Services/IUKMAuthenticationService/Login", ReplyAction="http://www.UKMail.com/Services/Contracts/ServiceContracts/IUKMAuthenticationServi" +
            "ce/LoginResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReferenceUKMailQA.UKMLoginResponse> LoginAsync(WebApplication1.ServiceReferenceUKMailQA.LoginWebRequest loginWebRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UKMail.com/Services/IUKMAuthenticationService/Logout", ReplyAction="http://www.UKMail.com/Services/Contracts/ServiceContracts/IUKMAuthenticationServi" +
            "ce/LogoutResponse")]
        WebApplication1.ServiceReferenceUKMailQA.UKMLogoutResponse Logout(WebApplication1.ServiceReferenceUKMailQA.WebRequest webRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UKMail.com/Services/IUKMAuthenticationService/Logout", ReplyAction="http://www.UKMail.com/Services/Contracts/ServiceContracts/IUKMAuthenticationServi" +
            "ce/LogoutResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReferenceUKMailQA.UKMLogoutResponse> LogoutAsync(WebApplication1.ServiceReferenceUKMailQA.WebRequest webRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUKMAuthenticationServiceChannel : WebApplication1.ServiceReferenceUKMailQA.IUKMAuthenticationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UKMAuthenticationServiceClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReferenceUKMailQA.IUKMAuthenticationService>, WebApplication1.ServiceReferenceUKMailQA.IUKMAuthenticationService {
        
        public UKMAuthenticationServiceClient() {
        }
        
        public UKMAuthenticationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UKMAuthenticationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UKMAuthenticationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UKMAuthenticationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplication1.ServiceReferenceUKMailQA.UKMLoginResponse Login(WebApplication1.ServiceReferenceUKMailQA.LoginWebRequest loginWebRequest) {
            return base.Channel.Login(loginWebRequest);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReferenceUKMailQA.UKMLoginResponse> LoginAsync(WebApplication1.ServiceReferenceUKMailQA.LoginWebRequest loginWebRequest) {
            return base.Channel.LoginAsync(loginWebRequest);
        }
        
        public WebApplication1.ServiceReferenceUKMailQA.UKMLogoutResponse Logout(WebApplication1.ServiceReferenceUKMailQA.WebRequest webRequest) {
            return base.Channel.Logout(webRequest);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReferenceUKMailQA.UKMLogoutResponse> LogoutAsync(WebApplication1.ServiceReferenceUKMailQA.WebRequest webRequest) {
            return base.Channel.LogoutAsync(webRequest);
        }
    }
}
