//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.UKMCollectionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebRequest", Namespace="http://www.UKMail.com/Services/Contracts/DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.UKMCollectionService.AddCollectionWebRequest))]
    public partial class WebRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AuthenticationTokenField;
        
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AuthenticationToken {
            get {
                return this.AuthenticationTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationTokenField, value) != true)) {
                    this.AuthenticationTokenField = value;
                    this.RaisePropertyChanged("AuthenticationToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddCollectionWebRequest", Namespace="http://www.UKMail.com/Services/Contracts/DataContracts")]
    [System.SerializableAttribute()]
    public partial class AddCollectionWebRequest : WebApplication1.UKMCollectionService.WebRequest {
        
        private string AccountNumberField;
        
        private bool ClosedForLunchField;
        
        private System.DateTime EarliestTimeField;
        
        private System.DateTime LatestTimeField;
        
        private System.DateTime RequestedCollectionDateField;
        
        private string SpecialInstructionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ClosedForLunch {
            get {
                return this.ClosedForLunchField;
            }
            set {
                if ((this.ClosedForLunchField.Equals(value) != true)) {
                    this.ClosedForLunchField = value;
                    this.RaisePropertyChanged("ClosedForLunch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime EarliestTime {
            get {
                return this.EarliestTimeField;
            }
            set {
                if ((this.EarliestTimeField.Equals(value) != true)) {
                    this.EarliestTimeField = value;
                    this.RaisePropertyChanged("EarliestTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime LatestTime {
            get {
                return this.LatestTimeField;
            }
            set {
                if ((this.LatestTimeField.Equals(value) != true)) {
                    this.LatestTimeField = value;
                    this.RaisePropertyChanged("LatestTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime RequestedCollectionDate {
            get {
                return this.RequestedCollectionDateField;
            }
            set {
                if ((this.RequestedCollectionDateField.Equals(value) != true)) {
                    this.RequestedCollectionDateField = value;
                    this.RaisePropertyChanged("RequestedCollectionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SpecialInstructions {
            get {
                return this.SpecialInstructionsField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecialInstructionsField, value) != true)) {
                    this.SpecialInstructionsField = value;
                    this.RaisePropertyChanged("SpecialInstructions");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UKMWebResponse", Namespace="http://www.UKMail.com/Services/Contracts/DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.UKMCollectionService.UKMAddCollectionWebResponse))]
    public partial class UKMWebResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.UKMCollectionService.UKMWebError[] ErrorsField;
        
        private WebApplication1.UKMCollectionService.UKMResultState ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.UKMCollectionService.UKMWebWarning[] WarningsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.UKMCollectionService.UKMWebError[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebApplication1.UKMCollectionService.UKMResultState Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.UKMCollectionService.UKMWebWarning[] Warnings {
            get {
                return this.WarningsField;
            }
            set {
                if ((object.ReferenceEquals(this.WarningsField, value) != true)) {
                    this.WarningsField = value;
                    this.RaisePropertyChanged("Warnings");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UKMAddCollectionWebResponse", Namespace="http://www.UKMail.com/Services/Contracts/DataContracts")]
    [System.SerializableAttribute()]
    public partial class UKMAddCollectionWebResponse : WebApplication1.UKMCollectionService.UKMWebResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookingMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CollectionJobNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookingMessage {
            get {
                return this.BookingMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingMessageField, value) != true)) {
                    this.BookingMessageField = value;
                    this.RaisePropertyChanged("BookingMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CollectionJobNumber {
            get {
                return this.CollectionJobNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CollectionJobNumberField, value) != true)) {
                    this.CollectionJobNumberField = value;
                    this.RaisePropertyChanged("CollectionJobNumber");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UKMWebError", Namespace="http://www.UKMail.com/Services/Contracts/DataContracts")]
    [System.SerializableAttribute()]
    public partial class UKMWebError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UKMResultState", Namespace="http://schemas.datacontract.org/2004/07/UKMWebAPICommon.WebResponses")]
    public enum UKMResultState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Successful = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UKMWebWarning", Namespace="http://www.UKMail.com/Services/Contracts/DataContracts")]
    [System.SerializableAttribute()]
    public partial class UKMWebWarning : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.UKMail.com/Services/Contracts/ServiceContracts", ConfigurationName="UKMCollectionService.IUKMCollectionService")]
    public interface IUKMCollectionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UKMail.com/Services/IUKMCollectionService/BookCollection", ReplyAction="http://www.UKMail.com/Services/Contracts/ServiceContracts/IUKMCollectionService/B" +
            "ookCollectionResponse")]
        WebApplication1.UKMCollectionService.UKMAddCollectionWebResponse BookCollection(WebApplication1.UKMCollectionService.AddCollectionWebRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.UKMail.com/Services/IUKMCollectionService/BookCollection", ReplyAction="http://www.UKMail.com/Services/Contracts/ServiceContracts/IUKMCollectionService/B" +
            "ookCollectionResponse")]
        System.Threading.Tasks.Task<WebApplication1.UKMCollectionService.UKMAddCollectionWebResponse> BookCollectionAsync(WebApplication1.UKMCollectionService.AddCollectionWebRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUKMCollectionServiceChannel : WebApplication1.UKMCollectionService.IUKMCollectionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UKMCollectionServiceClient : System.ServiceModel.ClientBase<WebApplication1.UKMCollectionService.IUKMCollectionService>, WebApplication1.UKMCollectionService.IUKMCollectionService {
        
        public UKMCollectionServiceClient() {
        }
        
        public UKMCollectionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UKMCollectionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UKMCollectionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UKMCollectionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplication1.UKMCollectionService.UKMAddCollectionWebResponse BookCollection(WebApplication1.UKMCollectionService.AddCollectionWebRequest request) {
            return base.Channel.BookCollection(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.UKMCollectionService.UKMAddCollectionWebResponse> BookCollectionAsync(WebApplication1.UKMCollectionService.AddCollectionWebRequest request) {
            return base.Channel.BookCollectionAsync(request);
        }
    }
}
